from run_commands.multi_label.usage import naive_usage

if __name__ == '__main__':
    naive_usage(
        dataset_name="cifar10",
        crit="BCE",
        py_file="multi_class_batch_learning.py",
        seed_list=[2222],
        epoch=45,
        batch_size=192,
        opt="sgd",
        cu=1,
        lr=0.01,
    )
    naive_usage(
        dataset_name="cifar10",
        crit="ReWeighted",
        py_file="multi_class_batch_learning.py",
        seed_list=[2222],
        epoch=45,
        batch_size=192,
        opt="sgd",
        cu=1,
        lr=0.01,
    )
    naive_usage(
        dataset_name="cifar100",
        crit="BCE",
        py_file="multi_class_batch_learning.py",
        seed_list=[2222],
        epoch=50,
        batch_size=192,
        opt="sgd",
        cu=1,
        lr=0.01,
    )
    naive_usage(
        dataset_name="cifar100",
        crit="ReWeighted",
        py_file="multi_class_batch_learning.py",
        seed_list=[2222],
        epoch=50,
        batch_size=192,
        opt="sgd",
        cu=1,
        lr=0.01,
    )
    naive_usage(
        dataset_name="tinyimagenet",
        crit="BCE",
        py_file="multi_class_batch_learning.py",
        seed_list=[2222],
        epoch=55,
        batch_size=192,
        opt="sgd",
        cu=1,
        lr=0.01,
    )
    naive_usage(
        dataset_name="tinyimagenet",
        crit="ReWeighted",
        py_file="multi_class_batch_learning.py",
        seed_list=[2222],
        epoch=55,
        batch_size=192,
        opt="sgd",
        cu=1,
        lr=0.01,
    )

